# Generated by Django 5.2.11 on 2026-02-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='reservation_date',
        ),
    ]
