# Generated by Django 5.2.11 on 2026-02-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_booking_date_booking_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_slot',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateTimeField(),
        ),
    ]
