# Generated by Django 5.2.11 on 2026-02-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_booking_reservation_slot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='first_name',
        ),
    ]
