# Generated by Django 5.2.11 on 2026-02-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_name_booking_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
